name: amass
version: git
summary: In-depth Attack Surface Mapping and Asset Discovery.
description: The OWASP Amass Project has developed a tool to help information security professionals perform network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques.
icon: images/snapcraft_icon.png

license: Apache-2.0	

base: core20
type: app
grade: stable
confinement: strict

apps:
  amass:
    command: bin/amass
    plugs:
      - home
      - network
      - removable-media
      - dot-amass

plugs:
  dot-amass:
    interface: personal-files
    write:
      - $HOME/.amass
      - $HOME/.config/amass

parts:
  amass:
    plugin: nil
    build-snaps: [go]
    source: .
    source-type: git
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      GO111MODULE=on go get github.com/OWASP/Amass/v3/...
      cp $GOBIN/amass $SNAPCRAFT_PRIME/bin/amass