name: docker

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "develop"

jobs:
  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - if: github.ref == 'refs/heads/master'
        id: meta_master
        uses: docker/metadata-action@v3
        with:
          images: caffix/amass
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
      - if: github.ref == 'refs/heads/develop'
        id: meta_develop
        uses: docker/metadata-action@v3
        with:
          images: caffix/amass
          tags: |
            type=raw,value=dev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: '${{ steps.meta_master.outputs.tags }}${{ steps.meta_develop.outputs.tags }}'
          labels: '${{ steps.meta_master.outputs.labels }}${{ steps.meta_develop.outputs.labels }}'
